version: "3.8"

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: healthcare
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iot-network

  # Broker MQTT
  mqtt-broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt-broker:/mosquitto/config
    networks:
      - iot-network

  # IoT Gateway
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "5000:5000" # REST
      - "5001:5001" # gRPC
      - "5002:5002" # WebSocket
    depends_on:
      - mqtt-broker
    environment:
      MQTT_PREFIX: "data/healthcare"
    networks:
      - iot-network

  # Subscriptor MQTT
  subscriber:
    build: ./subscriber
    container_name: subscriber
    depends_on:
      - mqtt-broker
      - postgres
    environment:
      MQTT_BROKER: "mqtt-broker"
      POSTGRES_HOST: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "healthcare"
      MQTT_PREFIX: "data/healthcare"
    networks:
      - iot-network

  # Sensor de temperatura (REST)
  sensor-temperature:
    build: ./sensor_temperature
    container_name: sensor-temperature
    depends_on:
      - gateway
    environment:
      GATEWAY_URL: "http://gateway:5000/temperature"
      PATIENT_ID: "1"
    networks:
      - iot-network

  # Sensor de ritmo cardíaco (gRPC)
  sensor-heartrate:
    build: ./sensor_heartrate
    container_name: sensor-heartrate
    depends_on:
      - gateway
    environment:
      GATEWAY_HOST: "gateway"
      GATEWAY_PORT: "5001"
      PATIENT_ID: "2"
    networks:
      - iot-network

  # Sensor de presión arterial (WebSocket)
  sensor-bloodpressure:
    build: ./sensor_bloodpressure
    container_name: sensor-bloodpressure
    depends_on:
      - gateway
    environment:
      GATEWAY_WS_URL: "ws://gateway:5002/bloodpressure"
      PATIENT_ID: "3"
    networks:
      - iot-network

volumes:
  postgres_data:

networks:
  iot-network:
    driver: bridge
