version: "3.9"

services:
  # 🟢 MQTT Broker - Mosquitto
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001" # WebSocket (opcional)
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  # 🟡 Base de Datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: iotuser
      POSTGRES_PASSWORD: iotpass
      POSTGRES_DB: health_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # 🧠 Gateway IoT - recibe REST, gRPC y WebSocket
  gateway:
    build: ./gateway
    container_name: iot-gateway
    ports:
      - "5000:5000" # REST
      - "5001:5001" # gRPC
      - "5002:5002" # WebSocket
    depends_on:
      - mqtt-broker
    restart: unless-stopped

  # 📥 Subscriber MQTT -> PostgreSQL
  subscriber:
    build: ./subscriber
    container_name: mqtt-subscriber
    depends_on:
      - mqtt-broker
      - postgres
    restart: unless-stopped

  # 🔴 Sensor REST
  sensor-rest:
    build: ./sensors/rest
    container_name: sensor-rest
    environment:
      - INTERVALO_SEGUNDOS=60
    depends_on:
      - gateway
    restart: unless-stopped

  # 🔵 Sensor gRPC
  sensor-grpc:
    build: ./sensors/grpc
    container_name: sensor-grpc
    environment:
      - INTERVALO_SEGUNDOS=60
    depends_on:
      - gateway
    restart: unless-stopped

  # 🟣 Sensor WebSocket
  sensor-ws:
    build: ./sensors/websocket
    container_name: sensor-ws
    environment:
      - INTERVALO_SEGUNDOS=60
    depends_on:
      - gateway
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
  postgres_data:
