@echo off
echo Deteniendo proyecto IoT de salud...
docker-compose down -v
echo Eliminando contenedores huérfanos...
docker-compose rm -fsv
echo Limpiando recursos no utilizados...
docker system prune -f
pause